/*
 * PaymentsAPI
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.bankanovafx.payments.api.controllers;

import static org.junit.Assert.*;

import java.io.*;
import java.util.*;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

import com.bankanovafx.payments.api.models.*;
import com.bankanovafx.payments.api.exceptions.*;
import com.bankanovafx.payments.api.APIHelper;
import com.bankanovafx.payments.api.Configuration;
import com.bankanovafx.payments.api.testing.TestHelper;
import com.bankanovafx.payments.api.controllers.PaymentsController;

import com.fasterxml.jackson.core.type.TypeReference;

public class PaymentsControllerTest extends ControllerTestBase {
    
    /**
     * Controller instance (for all tests)
     */
    private static PaymentsController controller;
    
    /**
     * Setup test class
     */
    @BeforeClass
    public static void setUpClass() {
        controller = getClient().getPayments();
    }

    /**
     * Tear down test class
     * @throws IOException
     */
    @AfterClass
    public static void tearDownClass() throws IOException {
        controller = null;
    }

}
