/*
 * PaymentsAPI
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.bankanovafx.payments.api.exceptions;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.bankanovafx.payments.api.http.client.HttpContext;

public class RequestErrorException 
        extends APIException
        implements java.io.Serializable {
    private static final long serialVersionUID = 81696758779627501L;
    private String message;
    /** GETTER
     * Message indicating the source of the error in the request
     */
    @JsonGetter("message")
    public String getMessage ( ) { 
        return this.message;
    }
    
    /** SETTER
     * Message indicating the source of the error in the request
     */
    @JsonSetter("message")
    private void setMessage (String value) { 
        this.message = value;
    }
 
    /**
     * Initialization constructor
     * @param   reason  The reason for throwing exception
     * @param   context The http context of the API exception
     */
    public RequestErrorException(String reason, HttpContext context) {
        super(reason, context);
    }
}
