/*
 * PaymentsAPI
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.bankanovafx.payments.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Address 
        implements java.io.Serializable {
    private static final long serialVersionUID = -2971512891101204612L;
    private String address1;
    private String address2;
    private String city;
    private String state;
    private String postalCode;
    private String country;
    /** GETTER
     * Address Line 1
     */
    @JsonGetter("address1")
    public String getAddress1 ( ) { 
        return this.address1;
    }
    
    /** SETTER
     * Address Line 1
     */
    @JsonSetter("address1")
    public void setAddress1 (String value) { 
        this.address1 = value;
    }
 
    /** GETTER
     * Address Line 2
     */
    @JsonGetter("address2")
    public String getAddress2 ( ) { 
        return this.address2;
    }
    
    /** SETTER
     * Address Line 2
     */
    @JsonSetter("address2")
    public void setAddress2 (String value) { 
        this.address2 = value;
    }
 
    /** GETTER
     * City
     */
    @JsonGetter("city")
    public String getCity ( ) { 
        return this.city;
    }
    
    /** SETTER
     * City
     */
    @JsonSetter("city")
    public void setCity (String value) { 
        this.city = value;
    }
 
    /** GETTER
     * State / Province
     */
    @JsonGetter("state")
    public String getState ( ) { 
        return this.state;
    }
    
    /** SETTER
     * State / Province
     */
    @JsonSetter("state")
    public void setState (String value) { 
        this.state = value;
    }
 
    /** GETTER
     * Postal Code
     */
    @JsonGetter("postalCode")
    public String getPostalCode ( ) { 
        return this.postalCode;
    }
    
    /** SETTER
     * Postal Code
     */
    @JsonSetter("postalCode")
    public void setPostalCode (String value) { 
        this.postalCode = value;
    }
 
    /** GETTER
     * Country (ISO 3166-1 Alpha-2 Code)
     */
    @JsonGetter("country")
    public String getCountry ( ) { 
        return this.country;
    }
    
    /** SETTER
     * Country (ISO 3166-1 Alpha-2 Code)
     */
    @JsonSetter("country")
    public void setCountry (String value) { 
        this.country = value;
    }
 
}
