/*
 * PaymentsAPI
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.bankanovafx.payments.api.models;

import java.util.*;

public class AddressBuilder {
    //the instance to build
    private Address address;

    /**
     * Default constructor to initialize the instance
     */
    public AddressBuilder() {
        address = new Address();
    }

    /**
     * Address Line 1
     */
    public AddressBuilder address1(String address1) {
        address.setAddress1(address1);
        return this;
    }

    /**
     * Address Line 2
     */
    public AddressBuilder address2(String address2) {
        address.setAddress2(address2);
        return this;
    }

    /**
     * City
     */
    public AddressBuilder city(String city) {
        address.setCity(city);
        return this;
    }

    /**
     * State / Province
     */
    public AddressBuilder state(String state) {
        address.setState(state);
        return this;
    }

    /**
     * Postal Code
     */
    public AddressBuilder postalCode(String postalCode) {
        address.setPostalCode(postalCode);
        return this;
    }

    /**
     * Country (ISO 3166-1 Alpha-2 Code)
     */
    public AddressBuilder country(String country) {
        address.setCountry(country);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Address build() {
        return address;
    }
}