/*
 * PaymentsAPI
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.bankanovafx.payments.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Bank 
        implements java.io.Serializable {
    private static final long serialVersionUID = 1868053728814816749L;
    private String name;
    private Address address;
    private String routingCode;
    private String swiftCode;
    /** GETTER
     * Bank Name
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * Bank Name
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * Address Information
     */
    @JsonGetter("address")
    public Address getAddress ( ) { 
        return this.address;
    }
    
    /** SETTER
     * Address Information
     */
    @JsonSetter("address")
    public void setAddress (Address value) { 
        this.address = value;
    }
 
    /** GETTER
     * Routing Code. Currently only supported for USD wires. When using, please only provide SWIFT code OR routing code (not both)
     */
    @JsonGetter("routingCode")
    public String getRoutingCode ( ) { 
        return this.routingCode;
    }
    
    /** SETTER
     * Routing Code. Currently only supported for USD wires. When using, please only provide SWIFT code OR routing code (not both)
     */
    @JsonSetter("routingCode")
    public void setRoutingCode (String value) { 
        this.routingCode = value;
    }
 
    /** GETTER
     * SWIFT BIC
     */
    @JsonGetter("swiftCode")
    public String getSwiftCode ( ) { 
        return this.swiftCode;
    }
    
    /** SETTER
     * SWIFT BIC
     */
    @JsonSetter("swiftCode")
    public void setSwiftCode (String value) { 
        this.swiftCode = value;
    }
 
}
