/*
 * PaymentsAPI
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.bankanovafx.payments.api.models;

import java.util.*;

public class BankBuilder {
    //the instance to build
    private Bank bank;

    /**
     * Default constructor to initialize the instance
     */
    public BankBuilder() {
        bank = new Bank();
    }

    /**
     * Bank Name
     */
    public BankBuilder name(String name) {
        bank.setName(name);
        return this;
    }

    /**
     * Address Information
     */
    public BankBuilder address(Address address) {
        bank.setAddress(address);
        return this;
    }

    /**
     * Routing Code. Currently only supported for USD wires. When using, please only provide SWIFT code OR routing code (not both)
     */
    public BankBuilder routingCode(String routingCode) {
        bank.setRoutingCode(routingCode);
        return this;
    }

    /**
     * SWIFT BIC
     */
    public BankBuilder swiftCode(String swiftCode) {
        bank.setSwiftCode(swiftCode);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Bank build() {
        return bank;
    }
}