/*
 * PaymentsAPI
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.bankanovafx.payments.api.models;

import java.util.*;

public class BankAccountBuilder {
    //the instance to build
    private BankAccount bankAccount;

    /**
     * Default constructor to initialize the instance
     */
    public BankAccountBuilder() {
        bankAccount = new BankAccount();
    }

    /**
     * Bank Account Number / IBAN. Required for Beneficiary Bank. Optional for Intermediary Bank.
     */
    public BankAccountBuilder accountNumber(String accountNumber) {
        bankAccount.setAccountNumber(accountNumber);
        return this;
    }

    /**
     * Bank Information Object
     */
    public BankAccountBuilder bank(Bank bank) {
        bankAccount.setBank(bank);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public BankAccount build() {
        return bankAccount;
    }
}