/*
 * PaymentsAPI
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.bankanovafx.payments.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class BankAccount 
        implements java.io.Serializable {
    private static final long serialVersionUID = 1190840771531138786L;
    private String accountNumber;
    private Bank bank;
    /** GETTER
     * Bank Account Number / IBAN. Required for Beneficiary Bank. Optional for Intermediary Bank.
     */
    @JsonGetter("accountNumber")
    public String getAccountNumber ( ) { 
        return this.accountNumber;
    }
    
    /** SETTER
     * Bank Account Number / IBAN. Required for Beneficiary Bank. Optional for Intermediary Bank.
     */
    @JsonSetter("accountNumber")
    public void setAccountNumber (String value) { 
        this.accountNumber = value;
    }
 
    /** GETTER
     * Bank Information Object
     */
    @JsonGetter("bank")
    public Bank getBank ( ) { 
        return this.bank;
    }
    
    /** SETTER
     * Bank Information Object
     */
    @JsonSetter("bank")
    public void setBank (Bank value) { 
        this.bank = value;
    }
 
}
