/*
 * PaymentsAPI
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.bankanovafx.payments.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Beneficiary 
        implements java.io.Serializable {
    private static final long serialVersionUID = 2049292313291625702L;
    private String name;
    private Address address;
    private String email;
    private String phoneNumber;
    /** GETTER
     * Beneficiary Name
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * Beneficiary Name
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * Address Information
     */
    @JsonGetter("address")
    public Address getAddress ( ) { 
        return this.address;
    }
    
    /** SETTER
     * Address Information
     */
    @JsonSetter("address")
    public void setAddress (Address value) { 
        this.address = value;
    }
 
    /** GETTER
     * Beneficiary Email Address
     */
    @JsonGetter("email")
    public String getEmail ( ) { 
        return this.email;
    }
    
    /** SETTER
     * Beneficiary Email Address
     */
    @JsonSetter("email")
    public void setEmail (String value) { 
        this.email = value;
    }
 
    /** GETTER
     * Beneficiary Phone Number
     */
    @JsonGetter("phoneNumber")
    public String getPhoneNumber ( ) { 
        return this.phoneNumber;
    }
    
    /** SETTER
     * Beneficiary Phone Number
     */
    @JsonSetter("phoneNumber")
    public void setPhoneNumber (String value) { 
        this.phoneNumber = value;
    }
 
}
