/*
 * PaymentsAPI
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.bankanovafx.payments.api.models;

import java.util.*;

public class BeneficiaryBuilder {
    //the instance to build
    private Beneficiary beneficiary;

    /**
     * Default constructor to initialize the instance
     */
    public BeneficiaryBuilder() {
        beneficiary = new Beneficiary();
    }

    /**
     * Beneficiary Name
     */
    public BeneficiaryBuilder name(String name) {
        beneficiary.setName(name);
        return this;
    }

    /**
     * Address Information
     */
    public BeneficiaryBuilder address(Address address) {
        beneficiary.setAddress(address);
        return this;
    }

    /**
     * Beneficiary Email Address
     */
    public BeneficiaryBuilder email(String email) {
        beneficiary.setEmail(email);
        return this;
    }

    /**
     * Beneficiary Phone Number
     */
    public BeneficiaryBuilder phoneNumber(String phoneNumber) {
        beneficiary.setPhoneNumber(phoneNumber);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Beneficiary build() {
        return beneficiary;
    }
}