/*
 * PaymentsAPI
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.bankanovafx.payments.api.models;

import java.util.*;

public class OriginatorBuilder {
    //the instance to build
    private Originator originator;

    /**
     * Default constructor to initialize the instance
     */
    public OriginatorBuilder() {
        originator = new Originator();
    }

    /**
     * Originator Name
     */
    public OriginatorBuilder name(String name) {
        originator.setName(name);
        return this;
    }

    /**
     * Address Information
     */
    public OriginatorBuilder address(Address address) {
        originator.setAddress(address);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Originator build() {
        return originator;
    }
}