/*
 * PaymentsAPI
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.bankanovafx.payments.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class PaymentDetails 
        implements java.io.Serializable {
    private static final long serialVersionUID = 8464659866810924155L;
    private String purposeOfPayment;
    private String memo;
    private String paymentReference;
    /** GETTER
     * Purpose of payment
     */
    @JsonGetter("purposeOfPayment")
    public String getPurposeOfPayment ( ) { 
        return this.purposeOfPayment;
    }
    
    /** SETTER
     * Purpose of payment
     */
    @JsonSetter("purposeOfPayment")
    public void setPurposeOfPayment (String value) { 
        this.purposeOfPayment = value;
    }
 
    /** GETTER
     * Memo from Originator to Beneficiary
     */
    @JsonGetter("memo")
    public String getMemo ( ) { 
        return this.memo;
    }
    
    /** SETTER
     * Memo from Originator to Beneficiary
     */
    @JsonSetter("memo")
    public void setMemo (String value) { 
        this.memo = value;
    }
 
    /** GETTER
     * Payment Reference Information. Typically includes FI to FI notes
     */
    @JsonGetter("paymentReference")
    public String getPaymentReference ( ) { 
        return this.paymentReference;
    }
    
    /** SETTER
     * Payment Reference Information. Typically includes FI to FI notes
     */
    @JsonSetter("paymentReference")
    public void setPaymentReference (String value) { 
        this.paymentReference = value;
    }
 
}
