/*
 * PaymentsAPI
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.bankanovafx.payments.api.models;

import java.util.*;

public class PaymentDetailsBuilder {
    //the instance to build
    private PaymentDetails paymentDetails;

    /**
     * Default constructor to initialize the instance
     */
    public PaymentDetailsBuilder() {
        paymentDetails = new PaymentDetails();
    }

    /**
     * Purpose of payment
     */
    public PaymentDetailsBuilder purposeOfPayment(String purposeOfPayment) {
        paymentDetails.setPurposeOfPayment(purposeOfPayment);
        return this;
    }

    /**
     * Memo from Originator to Beneficiary
     */
    public PaymentDetailsBuilder memo(String memo) {
        paymentDetails.setMemo(memo);
        return this;
    }

    /**
     * Payment Reference Information. Typically includes FI to FI notes
     */
    public PaymentDetailsBuilder paymentReference(String paymentReference) {
        paymentDetails.setPaymentReference(paymentReference);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PaymentDetails build() {
        return paymentDetails;
    }
}