/*
 * PaymentsAPI
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.bankanovafx.payments.api.models;

import java.util.*;

public class PaymentBuilder {
    //the instance to build
    private Payment payment;

    /**
     * Default constructor to initialize the instance
     */
    public PaymentBuilder() {
        payment = new Payment();
    }

    /**
     * Payment ID
     */
    public PaymentBuilder id(Integer id) {
        payment.setId(id);
        return this;
    }

    /**
     * Quote ID
     */
    public PaymentBuilder quoteId(int quoteId) {
        payment.setQuoteId(quoteId);
        return this;
    }

    /**
     * Originator Information Object
     */
    public PaymentBuilder originator(Originator originator) {
        payment.setOriginator(originator);
        return this;
    }

    /**
     * Bank Account Information Object. **NOTE** - originatorBankAccount bank data should not be provided when creating a new Payment. This information is retrieved from the database based on the provided bank ID.**NOTE** - bank object is required for all BankAccount objects except originatorBankAccount
     */
    public PaymentBuilder originatorBankAccount(BankAccount originatorBankAccount) {
        payment.setOriginatorBankAccount(originatorBankAccount);
        return this;
    }

    /**
     * Beneficiary Information Object
     */
    public PaymentBuilder beneficiary(Beneficiary beneficiary) {
        payment.setBeneficiary(beneficiary);
        return this;
    }

    /**
     * Bank Account Information Object. **NOTE** - originatorBankAccount bank data should not be provided when creating a new Payment. This information is retrieved from the database based on the provided bank ID.**NOTE** - bank object is required for all BankAccount objects except originatorBankAccount
     */
    public PaymentBuilder beneficiaryBankAccount(BankAccount beneficiaryBankAccount) {
        payment.setBeneficiaryBankAccount(beneficiaryBankAccount);
        return this;
    }

    /**
     * Bank Account Information Object. **NOTE** - originatorBankAccount bank data should not be provided when creating a new Payment. This information is retrieved from the database based on the provided bank ID.**NOTE** - bank object is required for all BankAccount objects except originatorBankAccount
     */
    public PaymentBuilder intermediaryBankAccount(BankAccount intermediaryBankAccount) {
        payment.setIntermediaryBankAccount(intermediaryBankAccount);
        return this;
    }

    /**
     * Payment Information Data
     */
    public PaymentBuilder details(PaymentDetails details) {
        payment.setDetails(details);
        return this;
    }

    /**
     * Payment Information Data
     */
    public PaymentBuilder status(PaymentStatus status) {
        payment.setStatus(status);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Payment build() {
        return payment;
    }
}