/*
 * PaymentsAPI
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.bankanovafx.payments.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class PaymentStatus 
        implements java.io.Serializable {
    private static final long serialVersionUID = -2527517611262565268L;
    private Boolean approved;
    private Boolean sent;
    /** GETTER
     * Set to true once the payment has been approved
     */
    @JsonGetter("approved")
    public Boolean getApproved ( ) { 
        return this.approved;
    }
    
    /** SETTER
     * Set to true once the payment has been approved
     */
    @JsonSetter("approved")
    public void setApproved (Boolean value) { 
        this.approved = value;
    }
 
    /** GETTER
     * Set to true once the payment has been sent
     */
    @JsonGetter("sent")
    public Boolean getSent ( ) { 
        return this.sent;
    }
    
    /** SETTER
     * Set to true once the payment has been sent
     */
    @JsonSetter("sent")
    public void setSent (Boolean value) { 
        this.sent = value;
    }
 
}
