/*
 * PaymentsAPI
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.bankanovafx.payments.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Quote 
        implements java.io.Serializable {
    private static final long serialVersionUID = 6421020900910683964L;
    private Integer id;
    private Double beneficiaryAmount;
    private String beneficiaryCurrency;
    private Double originatorAmount;
    private Boolean originatorAmountIsFixed;
    private Double exchangeRate;
    private Boolean locked;
    private Integer revision;
    /** GETTER
     * Quote ID
     */
    @JsonGetter("id")
    public Integer getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * Quote ID
     */
    @JsonSetter("id")
    public void setId (Integer value) { 
        this.id = value;
    }
 
    /** GETTER
     * Amount to send in beneficiary currency. Not required if originatorAmount is provided.
     */
    @JsonGetter("beneficiaryAmount")
    public Double getBeneficiaryAmount ( ) { 
        return this.beneficiaryAmount;
    }
    
    /** SETTER
     * Amount to send in beneficiary currency. Not required if originatorAmount is provided.
     */
    @JsonSetter("beneficiaryAmount")
    public void setBeneficiaryAmount (Double value) { 
        this.beneficiaryAmount = value;
    }
 
    /** GETTER
     * Beneficiary currency code in ISO 4217 format
     */
    @JsonGetter("beneficiaryCurrency")
    public String getBeneficiaryCurrency ( ) { 
        return this.beneficiaryCurrency;
    }
    
    /** SETTER
     * Beneficiary currency code in ISO 4217 format
     */
    @JsonSetter("beneficiaryCurrency")
    public void setBeneficiaryCurrency (String value) { 
        this.beneficiaryCurrency = value;
    }
 
    /** GETTER
     * Amount to send in originator currency. Not required if beneficiaryAmount is provided
     */
    @JsonGetter("originatorAmount")
    public Double getOriginatorAmount ( ) { 
        return this.originatorAmount;
    }
    
    /** SETTER
     * Amount to send in originator currency. Not required if beneficiaryAmount is provided
     */
    @JsonSetter("originatorAmount")
    public void setOriginatorAmount (Double value) { 
        this.originatorAmount = value;
    }
 
    /** GETTER
     * If true, then the originator amount is fixed to the provided value. If false, then the beneficiary amount is fixed to the provided value. This field is automatically set based on whether the originator or beneficary amount was provided.
     */
    @JsonGetter("originatorAmountIsFixed")
    public Boolean getOriginatorAmountIsFixed ( ) { 
        return this.originatorAmountIsFixed;
    }
    
    /** SETTER
     * If true, then the originator amount is fixed to the provided value. If false, then the beneficiary amount is fixed to the provided value. This field is automatically set based on whether the originator or beneficary amount was provided.
     */
    @JsonSetter("originatorAmountIsFixed")
    private void setOriginatorAmountIsFixed (Boolean value) { 
        this.originatorAmountIsFixed = value;
    }
 
    /** GETTER
     * The exchange rate for the quote
     */
    @JsonGetter("exchangeRate")
    public Double getExchangeRate ( ) { 
        return this.exchangeRate;
    }
    
    /** SETTER
     * The exchange rate for the quote
     */
    @JsonSetter("exchangeRate")
    private void setExchangeRate (Double value) { 
        this.exchangeRate = value;
    }
 
    /** GETTER
     * Set to true if the quote rate is locked
     */
    @JsonGetter("locked")
    public Boolean getLocked ( ) { 
        return this.locked;
    }
    
    /** SETTER
     * Set to true if the quote rate is locked
     */
    @JsonSetter("locked")
    private void setLocked (Boolean value) { 
        this.locked = value;
    }
 
    /** GETTER
     * Quote revision number. This is automatically incremented each time the quote is refreshed or updated, and starts from 1
     */
    @JsonGetter("revision")
    public Integer getRevision ( ) { 
        return this.revision;
    }
    
    /** SETTER
     * Quote revision number. This is automatically incremented each time the quote is refreshed or updated, and starts from 1
     */
    @JsonSetter("revision")
    private void setRevision (Integer value) { 
        this.revision = value;
    }
 
}
