/*
 * PaymentsAPI
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.bankanovafx.payments.api.models;

import java.util.*;

public class QuoteBuilder {
    //the instance to build
    private Quote quote;

    /**
     * Default constructor to initialize the instance
     */
    public QuoteBuilder() {
        quote = new Quote();
    }

    /**
     * Quote ID
     */
    public QuoteBuilder id(Integer id) {
        quote.setId(id);
        return this;
    }

    /**
     * Amount to send in beneficiary currency. Not required if originatorAmount is provided.
     */
    public QuoteBuilder beneficiaryAmount(Double beneficiaryAmount) {
        quote.setBeneficiaryAmount(beneficiaryAmount);
        return this;
    }

    /**
     * Beneficiary currency code in ISO 4217 format
     */
    public QuoteBuilder beneficiaryCurrency(String beneficiaryCurrency) {
        quote.setBeneficiaryCurrency(beneficiaryCurrency);
        return this;
    }

    /**
     * Amount to send in originator currency. Not required if beneficiaryAmount is provided
     */
    public QuoteBuilder originatorAmount(Double originatorAmount) {
        quote.setOriginatorAmount(originatorAmount);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Quote build() {
        return quote;
    }
}