/*
 * PaymentsAPI
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.bankanovafx.payments.api;

import com.bankanovafx.payments.api.controllers.*;
import com.bankanovafx.payments.api.http.client.HttpClient;

public class PaymentsAPIClient {
    /**
     * Singleton access to Payments controller
     * @return	Returns the PaymentsController instance 
     */
    public PaymentsController getPayments() {
        return PaymentsController.getInstance();
    }

    /**
     * Singleton access to Quotes controller
     * @return	Returns the QuotesController instance 
     */
    public QuotesController getQuotes() {
        return QuotesController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public PaymentsAPIClient() {
    }

    /**
     * Client initialization constructor 
     */     
    public PaymentsAPIClient(String xApiKey) {
        this();
        Configuration.xApiKey = xApiKey;
    }
}